name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a5d5a2aea1c3733ebe8dd665ff05dbcaf4daeb1bac035842662987b8135ef3d"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
