name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b535961e816eb406c8a41a0f2ab769dfa79ab0422a6a2ae7da6ac6d55af5d2a"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
