name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "896162714e55c71540f3683eda8b75afdb743d0fe107ca008b2b7444eaf85b66"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
