name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea0d2a6bd18bf56cab087047b966f8f90de7f641d4e37a00814f4ca7ea7c5dd2"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
