name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88c9124ec310a171ecbf9203992fea000a5b792dbc6e4f6f7433ef74826d79b6"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
