name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c01b31d94a3d755ff0aedf2a98050ed481853c2b5a57b2dbc004765206c72dd"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
