name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64082e072bcae7d1a42fd7d9972f9cfbcf131d5837195723239a9d61696b753e"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
