name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "935da6bb2660fb8dfa8bb74475790e98413203b06f3876a13fa3a923cc3f982d"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
