name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29f65bd23a3d654c175e20b7a0225afa0c384e45fc8b9ebec33b2a2a4e19e66b"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
