name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21e0c4d6aded2b8d47548dff280026b4f5e4e53f7f74f778312630d2b588c8d4"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
