name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e3e69380327e8f9efafb9c265868c3cc5e7b71b6c21f80e725e4d43d3f770b1"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
