name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0c11c7cf8d93c7a1fa522c9c2ea23dee24d5b19604a2348eb02523d10641842"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
