name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fd4d4dcecda476180a6bd1fd67c8a85823c25f2bd1eb33db4f40a4efcf3b235"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
