name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df61c6bdf44e4cbe19a6b7a74e11b6b0b70948949c270d1ed2b9456f4419d18e"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
