name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e38403eaad1bf34c44758cc2b32a344527a3d51b0080f7e555d4dae5481dd90a"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
