name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5948c1a441b4fe948e1fc6f421ec0cc1e90432f10b2b0dcd86356f8ea9fc7a06"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
