name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "602e225ee061842906620c5e2a045ecd156a1b844e57b6532efc60c441ccfcdc"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
