name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea807d52d6fed03ac785a2346c6ae24911937c0be7e273b83c57d009c140fc38"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
