name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1532dc66947518d5a56b0e68f5a21b9fd9e4013802390657a2f724b0a28dacda"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
