name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae6432a4e96f8a1d1c49149174afafc8a318b9b726d0f0b5e89f721b288b6d49"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
