name = "DaxterCraft-Minecraft-Modpack"
author = "Cris83388"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd33057994ede530c6a0f8e5b68fa2448d27d4bc172165aee3a858f39a9629fc"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
